<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
    <PackageReference Include="DevExpress.Mvvm.CodeGenerators" Version="22.1.1" />
    <PackageReference Include="DevExpressMvvm" Version="24.1.6" />
  </ItemGroup>

</Project>
